SprocketBot/sprocket

- microservices/replay-parse-service/src/parser.py
- Make response checkers more safe by testing `status_code in response`, and using `dict.get` instead of `dict["str"]`
- Add retry loop to parse section
- Retry on all unknown errors (including 500s from ballchasing)
> feat: retry on 500 failures

- clients/web/src/lib/components/organisms/scrims/QueuedSubViews/PoppedView.svelte
- package-lock.json
Added classes to the card for Check-in to handle lg and 2xl screens in PoppedView.svelte
> CheckIn Overflow Fix

- clients/web/src/lib/components/molecules/scrims/AdminScrimTable.svelte
- core/config/default.json
I believe that this will fix the merge problems that were caused by request 136: 2jzecq7-2jzech2-2fzwkm2
> Fix merge errors

- clients/web/src/lib/components/atoms/Modal.svelte
- clients/web/src/lib/utils/actions/clickOutsideAction.ts
Worked with Shuk to resolve the issues with original implementation. Now works and is not an event listener factory of doom.
> Fix: Shukked it up and now it works

- .vscode/launch.json
- clients/web/src/lib/api/subscriptions/FollowReplayParse.subscription.ts
- clients/web/src/lib/components/organisms/scrims/modals/SubmitReplaysModal.svelte
- microservices/replay-parse-service/src/main.py
- microservices/replay-parse-service/src/parser.py
- microservices/replay-parse-service/src/progress.py
- microservices/submission-service/src/replay-submission/replay-submission.service.ts
Ticket:
https://app.clickup.com/t/2bbb8fz
Demo video:
https://user-images.githubusercontent.com/31896377/175838587-a4f20767-61e0-4ba8-a12b-fd56d25abcbb.mov
> Ballchasing retry progress updates

- core/src/identity/auth/oauth/oauth.controller.ts
- core/src/image-generation/image-generation.controller.ts
https://app.clickup.com/t/2qgbjvb
> fix: remove disused public endpoints.

- core/src/sprocket-rating/sprocket-rating.service.ts
https://datalore.jetbrains.com/notebook/qLmqVG4CwoP4NaCrWmjlf0/G3a3iCa0eQgMMREeXdQe1u/
> feat: update sprocket rating weights per new notebook

- clients/web/src/routes/__error.svelte
> feat: add error page

- clients/discord-bot/config/default.json
- clients/web/src/lib/components/atoms/FileInput.svelte
- clients/web/src/lib/components/organisms/scrims/modals/UploadReplaysModal.svelte
- microservices/matchmaking-service/config/default.json
- microservices/submission-service/config/default.json
Ticket: https://app.clickup.com/t/2tykcf1
- Fix broken replay removal
- Abstract file uniqueness and removal into `FileInput` component for better reusability
> Clicking X to remove replay cycles

- clients/web/src/lib/components/organisms/scrims/modals/CreateScrimModal.svelte
- Remove observable option
- Swap location of competitive and create group
> fix: remove observable option

- clients/web/.eslintrc.cjs
- clients/web/src/lib/api/queries/game-features/GameFeature.store.ts
- clients/web/src/lib/api/queries/game-features/SetGameFeature.mutation.ts
- clients/web/src/lib/api/queries/game-features/feature.types.ts
- clients/web/src/lib/api/queries/game-features/index.ts
- clients/web/src/lib/api/queries/index.ts
- clients/web/src/lib/components/molecules/AdminSettings/AdminSettings.svelte
- clients/web/src/lib/components/molecules/AdminSettings/GameFeatureToggle.svelte
- clients/web/src/lib/components/molecules/AdminSettings/index.ts
- clients/web/src/lib/components/molecules/index.ts
- clients/web/src/lib/components/molecules/scrims/AdminScrimTable.svelte
- clients/web/src/routes/admin/index.svelte
- core/src/game/game_feature/game_feature.service.ts
Ticket: https://app.clickup.com/t/3r8be0j
- Implement GameFeature query and mutation
- Create `<AdminSettings />`
- Toggle rankouts with GameFeature mutation
- Toggle scrims (moved from AdminScrimTable)
https://user-images.githubusercontent.com/31896377/189468858-46d1d7d9-6024-49e5-90fc-5d4332404bc0.mov
> Admin Settings [3r8be0j]

- clients/web/src/lib/components/organisms/scrims/QueuedSubViews/InProgressView.svelte
> feat: make rejections more obvious

- clients/image-generation-frontend/src/config.ts
- clients/image-generation-frontend/src/utils/rabbitmq.ts
- microservices/image-generation-service/src/image-generation/image-generation.controller.ts
- queries/image-generation/series/series_query.sql
image generation client now functions properly.
> Misc. Fixes for Image Generation Pipeline

- clients/web/src/lib/components/molecules/user-menu/UserMenu.svelte
> fix: ellipsis for long names on mobile

- clients/web/src/lib/api/queries/match/Match.store.ts
- clients/web/src/routes/league/[fixtureId].svelte
- clients/web/src/routes/league/submit/[submissionId].svelte
- core/src/scheduling/match-parent/match-parent.resolver.ts
- core/src/scheduling/match/match.resolver.ts
- core/src/scheduling/scheduling.module.ts
https://app.clickup.com/t/3yapuex
> Show match/fixture info on replay submit page

- clients/web/src/routes/scrims/index.svelte
- core/src/mledb/mledb-player/mledb-player.guard.ts
- core/src/scrim/scrim.mod.resolver.ts
> feat: don't let former players scrim [CU-3jtndyq]

- core/src/database/extended-repositories/repository.ts
- core/src/database/extended-repositories/similarity.input-type.ts
- core/src/database/types.ts
- core/src/organization/organization/organization.resolver.ts
> feat: search by similarity

- core/jest.config.js
- core/src/authorization/authorization.service.spec.helpers.ts
- core/src/authorization/authorization.service.spec.ts
> feat: authorization testing

- common/src/service-connectors/matchmaking/schemas/scrim/SetScrimLocked.schema.ts
- common/src/service-connectors/matchmaking/types/Scrim.ts
- core/src/internal/scrim/scrim.mod.resolver.ts
- core/src/internal/scrim/scrim.service.ts
- core/src/internal/scrim/types/Scrim.ts
- microservices/matchmaking-service/src/scrim/scrim-crud/scrim-crud.service.ts
- microservices/matchmaking-service/src/scrim/scrim.controller.ts
- microservices/matchmaking-service/src/scrim/scrim.event-subscriber.ts
- microservices/matchmaking-service/src/scrim/scrim.service.ts
adds a reason for why scrims are being locked
> feat: scrim locked reason [CU-3yw11q7]

- clients/web/src/lib/components/atoms/form/Select/Select.story.svelte
- clients/web/src/lib/components/atoms/form/Select/Select.svelte
- clients/web/src/lib/components/atoms/form/Select/index.ts
- clients/web/src/lib/components/atoms/form/index.ts
https://flowbite.com/docs/forms/select/
https://user-images.githubusercontent.com/31896377/200883084-22fba8cb-6c59-474f-8618-a981de8af8ba.mov
> Select form atom

- .vscode/launch.json
- clients/web/package.json
- clients/web/src/lib/components/atoms/form/FileInput/FileInput.story.svelte
- clients/web/src/lib/components/atoms/form/FileInput/FileInput.svelte
- clients/web/src/lib/components/atoms/form/FileInput/filedrop-svelte.d.ts
- clients/web/src/lib/components/atoms/form/FileInput/index.ts
- clients/web/src/lib/components/atoms/form/index.ts
- clients/web/tsconfig.json
- package-lock.json
https://flowbite.com/docs/forms/file-input/
https://user-images.githubusercontent.com/31896377/200934733-90733234-7960-43f3-83a6-c7640c64d8e6.mov
> File input and dropzone atom

- .vscode/settings.json
- clients/web/histoire.config.ts
- clients/web/src/lib/components/atoms/Accordion/Accordion.story.svelte
- clients/web/src/lib/components/atoms/Alert/Alert.story.svelte
- clients/web/src/lib/components/atoms/form/Checkbox/Checkbox.story.svelte
- clients/web/src/lib/components/atoms/form/Checkbox/Checkbox.svelte
- clients/web/src/lib/components/atoms/form/Checkbox/index.ts
- clients/web/src/lib/components/atoms/form/Input/Input.story.svelte
- clients/web/src/lib/components/atoms/form/Textarea/Textarea.story.svelte
https://flowbite.com/docs/forms/checkbox/
https://user-images.githubusercontent.com/31896377/200986829-41f1ed59-5a13-4fbf-809a-aecd3ddb9ed6.mov
> Checkbox form atom

- common/src/service-connectors/matchmaking/types/Scrim.ts
- core/src/internal/scrim/types/Scrim.ts
- microservices/matchmaking-service/src/scrim/scrim-crud/scrim-crud.service.ts
- microservices/matchmaking-service/src/scrim/scrim-logic/scrim-logic.service.ts
adds a timeoutAt timestamp for when a scrim will timeout
> feat: scrim timeoutAt [CU-2exeeqh]

- queries/history_tables/update_history_table.sql
Quotations were missing for select / insert statements 
Quotation was also needed for type casting
> Address `update_history_table` edge cases

- core/src/internal/scrim/scrim.mod.resolver.ts
- core/src/internal/scrim/types/JoinScrimInput.ts
- core/src/internal/scrim/types/index.ts
Moved args for joinScrim into JoinScrimInput.
> feat: scrim-join-args [CU-#43azujg]

- clients/web/src/lib/actions/clickOutside.action.ts
- clients/web/src/lib/components/atoms/Avatar/Avatar.story.svelte
- clients/web/src/lib/components/atoms/Dropdown/Dropdown.story.svelte
- clients/web/src/lib/components/atoms/Dropdown/Dropdown.svelte
- clients/web/src/lib/components/atoms/Dropdown/index.ts
- clients/web/src/lib/components/atoms/index.ts
- package-lock.json
both handle content and dropdown content are dynamic to keep the component unopinionated about it's content.
> Dropdown Atom

- clients/web/src/lib/components/abstract/Toast/Toast.svelte
- clients/web/src/lib/components/abstract/Toast/ToastContainer.svelte
> fix: prevent toasts from being wider than they should

- common/src/service-connectors/matchmaking/types/MatchmakingError.enum.ts
- microservices/matchmaking-service/src/scrim/scrim.service.ts
Don't add a player to a scrim that's already full.
> Fix: add scrim full check before pushing player into scrim players list

- core/src/identity/database/user-authentication-account.repository.ts
- core/src/scheduling/scheduling.module.ts
- core/src/scheduling/scrim/scrim-admin.resolver.ts
- core/src/scheduling/scrim/scrim.service.ts
Allows support to message players of a scrim.
Prevent support from needing to do this:
> feat: notify scrim players [CU-863fyx0gz]

- core/src/scheduling/finalization/rocket-league-finalization/rocket-league-finalization.service.ts
Scrim points were created by round rather than match.
> fix: triple scrim points [CU-863g029bc]

- microservices/submission-service/src/replay-validation/replay-validation.module.ts
Removing an import that was breaking Sprocket. Couldn't find any other instances of this import.
> bugfix: removing broken import

- core/src/identity/user/user.resolver.ts
- core/src/mledb/mledb-match/mledb-match.service.ts
Includes 1 commit: fix NCPs not correctly setting winning team name.
> Staging -> Main

- core/src/elo/elo-connector/elo-connector.types.ts
- core/src/elo/elo-connector/schemas/ManualEloChange.schema.ts
- core/src/elo/elo-connector/schemas/index.ts
- core/src/franchise/player/player.resolver.ts
- core/src/replay-parse/finalization/finalization.subscriber.ts
Allows LO to update folks' elo directly.
> Add mutation resolver for manual elo changes

- core/src/franchise/franchise/franchise.controller.ts
- core/src/franchise/franchise/franchise.service.ts
- core/src/franchise/player/player.resolver.ts
- core/src/scrim/scrim.service.ts
in all places where we try to get the franchises attached to a sprocket User, do so with their *memberId* in the organization.
> fix: Not FPs get called FP

- common/src/service-connectors/submission/schemas/CanSubmitReplays.schema.ts
- common/src/service-connectors/submission/schemas/ratification/CanRatifySubmission.schema.ts
- core/config/default.json
- core/src/organization/member/member.service.ts
- core/src/replay-parse/replay-parse.mod.resolver.ts
- core/src/replay-parse/replay-parse.module.ts
- core/src/replay-parse/replay-parse.service.ts
- core/src/scheduling/match/match.resolver.ts
- microservices/submission-service/src/replay-submission/replay-submission-util.service.ts
feat: franchise staff with mismatch user/member ids could see matches but not submit, make the rest of the pipeline use the right ID.
> The great ID unborking, part 2

- core/src/identity/auth/oauth/strategies/discord.strategy.ts
- core/src/identity/auth/oauth/strategies/oauth.jwt.refresh.strategy.ts
- core/src/mledb/mledb-player-account/mledb-player-account.service.ts
- core/src/organization/member-platform-account/member-platform-account.service.ts
- core/src/organization/member/member.mod.resolver.ts
- core/src/organization/member/member.resolver.ts
- core/src/organization/organization.module.ts
Allow anyone with access to update accounts in the DB, without needing main write access!!
> feat: altair endpoint to add player accounts

- clients/web/src/routes/(app)/org-manager/roles/+page.svelte
- clients/web/src/routes/(app)/org-manager/users/[userId]/PlayerBox.svelte
- clients/web/src/routes/(app)/scrims/+page.gql
- clients/web/src/routes/(app)/scrims/+page.svelte
- clients/web/src/routes/(app)/scrims/ScrimCreateModal.svelte
- clients/web/src/routes/(app)/scrims/ScrimList.svelte
- clients/web/src/routes/(app)/scrims/create-scrim.gql
- Notable change: Game dropdown on Create Scrim modal is restricted to games the current user is a player in
- Notable change: If the user has no players, they are not shown any information regarding scrims, but are presented with a blocking message instead
> chore: web tweaks

- core/src/identity/auth/oauth/oauth.controller.ts
- core/src/mledb/mledb-player-account/mledb-player-account.service.ts
- core/src/organization/member/member.mod.resolver.ts
> feat: add `updated_by` user id for auditing player account adds.

- core/src/scheduling/match/match.service.ts
Previously, standings datasets were incorrect/incomplete because the winning team was only set on the MLEDB schema.
> Have NCPs properly set `homeWon` in the Sprocket schema

- core/src/franchise/player/player.resolver.ts
- core/src/franchise/player/player.service.ts
- core/src/identity/auth/oauth/oauth.controller.ts
Let LO and crew self-serve:
- name changes
- discord account swaps
- forcing players to a given team
> Automate some more manual DB touches

- core/src/database/scheduling/saved_scrim/scrim.model.ts
- core/src/replay-parse/finalization/rocket-league/rocket-league-finalization.service.ts
Add competitive flag to the ScrimMeta table, and write it when we finalize a scrim.
> Update finalization to save competitive flag in scrims.

- common/src/service-connectors/matchmaking/matchmaking.service.ts
- common/src/service-connectors/matchmaking/matchmaking.types.ts
- common/src/service-connectors/matchmaking/schemas/scrim/CreateLFSScrim.schema.ts
- common/src/service-connectors/matchmaking/schemas/scrim/index.ts
- common/src/service-connectors/matchmaking/types/ScrimJoinOptions.ts
- core/src/scrim/constants.ts
- core/src/scrim/scrim.mod.resolver.ts
- core/src/scrim/scrim.service.ts
- core/src/scrim/types/CreateLFSScrimInput.ts
- core/src/scrim/types/index.ts
- microservices/matchmaking-service/src/scrim/game-order/game-order.service.ts
- microservices/matchmaking-service/src/scrim/scrim-crud/scrim-crud.service.ts
- microservices/matchmaking-service/src/scrim/scrim.controller.ts
- microservices/matchmaking-service/src/scrim/scrim.service.ts
- Add new types to Common for the new scrim type
- Add mutations in core to accept a request to create the new scrim type
- Add handlers in matchmaking to actually create it
No changes were necessary to submission, validation, or finalization, because they are all ambivalent to # of games played or other scrim parameters.
> LFS Scrim Backend Changes

- README.md
adding an extra prerequisite to the README for Windows users, and adjusted the scripts to keep the "./"
> README refinement
