common/src/celery/celery.service.ts
common/src/celery/types/schemas/stats/ballchasing/ballchasing.schema.ts

The zod schema for replay responses from Ballchasing was being used in `safeParse` mode, which returns a boolean for an error condition rather than throwing. However, on failure, we were simply returning the original object, thus bypassing the zod schema check.

feat: update schema for possibly null data from ballchasing

---

clients/image-generation-frontend/.gitignore
clients/image-generation-frontend/Dockerfile
clients/image-generation-frontend/src/config.template.json
clients/image-generation-frontend/src/config.ts

Fixes config setting for image-generation-frontend so that we can properly inject them into docker.
Also pulls the config file in from the right project

chore: move configs

---

microservices/replay-parse-service/requirements.txt

Reverts SprocketBot/sprocket#146

Revert "chore(deps): bump numpy from 1.18.2 to 1.22.0 in /microservices/replay-parse-service"

---

clients/web/src/lib/components/organisms/scrims/QueuedSubViews/InProgressView.svelte

fix: monospace lobby info to distinguish O and 0

---

clients/discord-bot/src/marshal/commands/command.decorator.ts

Use `name` from command decorator so that it doesn't make a difference if a user calls the command with different capitalization

fix: use name from commandSpec

---

microservices/replay-parse-service/config/default.json
microservices/replay-parse-service/src/analytics.py
microservices/replay-parse-service/src/main.py

- Each `_ms` value should be the value for just that stage of the parsing pipeline
- Add config `disableCache` (`false` by default) to allow testing without cache

Fix replay parse timing analytics

---

clients/web/src/hooks.ts
clients/web/src/lib/utils/constants.ts
clients/web/src/routes/auth/login.svelte
core/src/identity/auth/auth.module.ts
core/src/identity/auth/oauth/guards/jwt-refresh.guard.ts
core/src/identity/auth/oauth/oauth.controller.ts
core/src/identity/auth/oauth/oauth.service.ts
core/src/identity/auth/oauth/strategies/index.ts
core/src/identity/auth/oauth/strategies/oauth.jwt.refresh.strategy.ts
core/src/identity/auth/oauth/types/accesstoken.type.ts

Old behavior:
- Log in
- Get JWT from the backend, valid for 7 days from the first login. 
- After 7 days, you have to log in again, regardless of last usage.
New behavior:
- Log in
- Get JWT from the backend, valid for 30 minutes, as well as a refresh token valid for 7 days.
- If at any point after 30 minutes but before 7 days you refresh the app, sprocket will *automatically* refresh your tokens, and you'll be logged in for another 30 minutes (with a new refresh token, valid for 7 days from the *refresh point*)
Thus, the only way a user will have to start the authorization process from scratch is if they haven't used Sprocket in more than 7 days.

Implement refresh tokens for authentication

---

core/src/scheduling/match/match.resolver.ts
core/src/scheduling/match/match.service.ts

For data integrity purposes (particularly wrt to Elo), we want to have the ability to "hard reset" and reprocess all match data available from a given date/time. This command allows for the second half of that process (the first, deleting the desired elo data, must still be done manually).

Reprocess Matches

---

clients/discord-bot/src/main.ts
common/src/celery/celery.service.ts
common/src/filters/all-exceptions.filter.ts
common/src/filters/index.ts
common/src/index.ts
core/src/main.ts
microservices/image-generation-service/src/main.ts
microservices/matchmaking-service/src/main.ts
microservices/notification-service/src/main.ts
microservices/server-analytics-service/src/main.ts
microservices/submission-service/src/main.ts

- Don't throw error in celery callback, it doesn't get caught by anything
- Add global error handlers to all microservices
Celery callback throwing doesn't kill microservice
Timeout error (or other error) is caught by global handler and doesn't kill microservice

Uncaught errors killing services

---

clients/web/src/app.d.ts
clients/web/src/lib/components/atoms/StackBanner.svelte
clients/web/src/lib/components/atoms/index.ts
clients/web/src/lib/utils/config.ts
clients/web/src/lib/utils/types/Config.ts
clients/web/src/routes/__layout.svelte

- Adds a banner to the top of the page that appears when the environment is `dev` or `staging`, links to `app.sprocket.gg`
- Add `VITE_STACK` env to determine stack (pulumi stack, options are `local`, `dev`, `staging`, `main`)
- Set cookie when banner is dismissed, lasts for 1 day (to make it less annoying for people actually testing on dev/staging)
Warning banner
Warning banner hidden when cookie is set

feat: stack banner to warn on dev/staging

---

clients/web/src/hooks.ts
clients/web/src/routes/auth/login.svelte
clients/web/src/routes/auth/logout.svelte
common/src/util/config.ts
core/config/default.json
core/src/identity/auth/oauth/oauth.controller.ts
core/src/identity/auth/oauth/oauth.service.ts

I have intentionally left the expiry time on the JWT very short (1 minute) so that this is easy to test in staging. Once we're satisfied that this works properly for everyone I will cut another PR to change that expiry to a value we agree is more sensible.

Fix Refresh Tokens

---

clients/web/src/lib/components/atoms/form/Input/Input.svelte
clients/web/src/lib/components/atoms/form/Textarea/Textarea.story.svelte
clients/web/src/lib/components/atoms/form/Textarea/Textarea.svelte
clients/web/src/lib/components/atoms/form/Textarea/index.ts
clients/web/src/lib/components/atoms/form/index.ts

Adds `Textarea` form element. Very similar to `Input`.

[Form Atoms] `Textarea`

---

clients/web/histoire.config.ts
clients/web/src/lib/components/atoms/Accordion/Accordion.story.svelte
clients/web/src/lib/components/atoms/Alert/Alert.story.svelte
clients/web/src/lib/components/atoms/form/Input/Input.story.svelte
clients/web/src/lib/components/atoms/form/Input/Input.svelte
clients/web/src/lib/components/atoms/form/Textarea/Textarea.story.svelte
clients/web/src/lib/components/atoms/form/Textarea/Textarea.svelte
clients/web/src/lib/histoire/Props.svelte
clients/web/src/lib/histoire/index.ts
clients/web/src/lib/histoire/setup.ts
package-lock.json

- Move around histoire stuff to feature folder
- Add `<Props />` component to histoire folder to show props being passed to Svelte component from controls
- Add `value` data binding for Input and Textarea

Form data binding

---

core/src/franchise/player/player.service.ts

Salaries were saved to MLEDB only when a rankout was processed for a given player. Add code to save the new salaries even when there's no rankout.

Save salaries to mledb

---

microservices/matchmaking-service/src/scrim/scrim-crud/scrim-crud.service.ts

Fixes a bug where passing a skill group to GetAllScrims returns an array as empty.

fix: passing-skill-group-to-GetAllScrims [CU-#43gnqpb]

---

core/src/authentication/strategies/microsoft/microsoft.strategy.ts
core/src/mledb/mledb-scrim/mledb-finalization.service.ts

Role usages were being created by replay, not series and were being created for scrims.

fix: role usages for scrims [CU-42ttamp]

---

common/src/util/config.ts
core/config/default.json
core/src/authentication/strategies/jwt/jwt.strategy.ts

Allows you to set a token in your configuration file to authenticate for all requests without needing to set a token. Useful for testing subscriptions because you cannot provide authentication tokens in GQL Playground or Altair. Defaults to the token in the header before trying to use the config token so you can have "multiple users".

feat: default token

---

core/src/franchise/franchise/franchise.service.ts

Bug was discovered by MLE user Jdogg, who is a blizzard captain but couldn't submit/ratify. Logs showed:
Jdogg is one of a handful of captains who have this issue. Discovered that all players with this issue (correct perms, but still unable) had a mismatch between their Sprocket UserId and MemberId (not designed to match, but by happenstance often do for 80%+ of the current userbase). Explicitly getting UserId from the Member table for a given player fixes this.

Fix: Some franchise staff unable to submit or ratify matches

---

core/src/elo/elo-connector/elo-connector.types.ts
core/src/elo/elo-connector/schemas/CompactGraph.schema.ts
core/src/elo/elo-connector/schemas/index.ts
core/src/elo/elo.consumer.ts
core/src/elo/elo.resolver.ts

Adds a mutation to the elo controller, and a corresponding method to the elo consumer, all to kick off the newly created `compactGraph` job on the elo side. This will allow sprocket admins to, on demand, run a job to compact the elo graph down to a history size of 1.

Elo Graph Compaction

---

core/src/franchise/player/player.resolver.ts
core/src/franchise/player/player.service.ts

Effectively, we're splitting apart the old `intakePlayer` in player service. This method used to be an upsert: if the MLEID already exists, overwrite its data with the new input, and if it doesn't, create a new player/member/user. This has recently caused *a lot* of difficulty for support staff when one player's valid data was accidentally overwritten with another's. 
New design: `intakePlayer` *only* inserts. If the MLEID input already exists, throw an error. `updatePlayer` takes slightly different arguments, and *only* updates. If the MLEID input does not yet exist, throw an error. The hope is that this slight API change will cause enough attention to detail that our FA intake folks don't completely overwrite an existing player in the future. 
Next feature up is having MLEIDs …

Create new `updatePlayer` mutation for LO intake

---

core/src/franchise/player/player.resolver.ts
core/src/franchise/player/player.service.ts
core/src/franchise/player/player.types.ts
core/src/identity/user/user.resolver.ts
core/src/organization/member/member.service.ts

- Refactor player service (particularly the create MLE player function for default args)
- Add new mutation in user resolver, which:
- Registers a user and UAA
- Creates a member within MLE
- Loops over the input list of tuples of `(skill_group, salary)` to create a player for each corresponding game
- Creates a single MLE player with the last salary and player ID from that loop

Add multi-game support for user intake

---

microservices/matchmaking-service/config/default.json
microservices/matchmaking-service/src/scrim/game-order/game-order.service.ts

Initial thought was to go with Ruskey's algorithm for generating unique set partitions of a given size: this turned out to be unnecessarily complicated, so I fell back to a really basic power set expansion and filtered for the ones we wanted. It's horrible time complexity (literally O(2^n)), but n is 6 and we only do it on initialization. 
TL;DR - Fix the 'two people get stuck with each other each 3s scrim' problem.

Improve Matchmaking for 3s RR Scrims

---

clients/web/src/lib/api/mutations/scrims/CreateLFSScrim.mutation.ts
clients/web/src/lib/api/mutations/scrims/CreateScrim.mutation.ts
clients/web/src/lib/api/mutations/scrims/index.ts
clients/web/src/lib/api/queries/scrims/CurrentScrim.store.ts
clients/web/src/lib/api/queries/scrims/LFSScrims.store.ts
clients/web/src/lib/api/queries/scrims/PendingScrims.store.ts
clients/web/src/lib/api/queries/scrims/index.ts
clients/web/src/lib/components/molecules/scrims/ScrimTable.svelte
clients/web/src/lib/components/organisms/scrims/LFSScrimsView.svelte
clients/web/src/lib/components/organisms/scrims/modals/CreateLFSScrimModal.svelte
clients/web/src/lib/components/organisms/scrims/modals/CreateScrimModal.svelte
clients/web/src/lib/components/organisms/scrims/modals/index.ts
clients/web/src/lib/stores/navigation.store.ts
clients/web/src/routes/__layout.svelte
clients/web/src/routes/league/scrim/_layout.svelte
clients/web/src/routes/league/scrim/index.svelte
clients/web/tsconfig.json
common/src/service-connectors/matchmaking/schemas/scrim/CreateLFSScrim.schema.ts
common/src/service-connectors/matchmaking/types/ScrimSettings.ts
core/config/default.json
core/src/database/game/game.module.ts
core/src/scrim/scrim.mod.resolver.ts
core/src/scrim/scrim.service.ts
core/src/scrim/types/CreateLFSScrimInput.ts
core/src/scrim/types/ScrimSettings.ts
docker-compose.yaml
microservices/matchmaking-service/config/default.json
microservices/matchmaking-service/src/scrim/scrim.service.spec.helpers.ts
microservices/matchmaking-service/src/scrim/scrim.service.ts

Adds a new landing page for franchise staff to manage team scrims:
- CRUD ops
- Upload replays
Have verified all behavior locally *aside from submission*, as I don't have replay-parse up and running locally yet. That's the last PR before we go live with this to staging.

Front-end changes for LFS Scrims
